;;; azazel/elpa.el --- Azazel's ELPA specialization

(push 'ace-jump-mode esk/packages)
(push 'ansible esk/packages)
(push 'async esk/packages)
(push 'bbdb esk/packages)
(push 'dired-filter esk/packages)
(push 'dockerfile-mode esk/packages)
(push 'elpy-mode esk/packages)
(push 'emmet-mode esk/packages)
(push 'erc-hl-nicks esk/packages)
(push 'google-translate esk/packages)
(push 'jabber esk/packages)
(push 'less-css-mode esk/packages)
(push 'muse esk/packages)
(push 'nginx-mode esk/packages)
(push 'rainbow-mode esk/packages)
(push 'ranger esk/packages)
(push 'realgud esk/packages)
(push 's esk/packages)
(push 'swiper esk/packages)
(push 'treemacs esk/packages)
(push 'typescript-mode esk/packages)
(push 'w3m esk/packages)
(push 'zeal-at-point esk/packages)
(push 'zenburn-theme esk/packages)
